### PR TITLE
SQL databases pull request

### PR DESCRIPTION
**Pull request by AleWaweru**
- Installed PostgreSQL
- create a database and animal table
- performed action required in the project description
-
Screenshot (167)
Screenshot (171)

### CODE REVIEW

**Review by Davidosky007 — COMMENTED** [review]
Hi @AleWaweru 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't follow the Gitflow pattern Kindly create a pull request to compare your feature branch with the development branch and submit the link to that pull request via your Dashboard.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by abdulhamiid — CHANGES_REQUESTED** [review]
Hi @AleWaweru 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ ❌ ❌ 
 
- [ ] As stated by the previous reviewer, please make sure that you used the correct [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md). 🤗

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by AleWaweru** [comment]
@abdulhamiid I created the dev branch, how else do you want me to do the work?

**Review by Ibizugbe — COMMENTED** [review]
Hi @AleWaweru 👋🏼, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't make use of the right gitflow practice. You have currently opened a PR from your feature branch (sql-data) to the main branch. meanwhile, using gitflow rightly requires you make the `dev` branch the default branch and open a pull request from the feature branch (sql-data) to the `dev` branch. I can see you have created a `dev` branch and you made it the default branch. but you should kindly ensure you are comparing the feature branch (sql-data) to the `dev` branch.😉

I hope this helps😉

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request merged**
